// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilsBot.Datenbank;

#nullable disable

namespace UtilsBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20251230220008_2primarykeys")]
    partial class _2primarykeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("UtilsBot.Domain.AllgemeinePerson", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GetsSoMuchXpRightNow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTimeInChannel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastXpGainDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Xp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpTodayByMessages")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "GuildId");

                    b.ToTable("AllgemeinePersonen");
                });
#pragma warning restore 612, 618
        }
    }
}
