// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilsBot.Datenbank;

#nullable disable

namespace UtilsBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260613100000_WarEraSubscriptionIncludePro")]
    partial class WarEraSubscriptionIncludePro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("UtilsBot.Domain.AllgemeinePerson", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GetsSoMuchXpRightNow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTimeInChannel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastXpGainDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Xp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpTodayByMessages")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "GuildId");

                    b.ToTable("AllgemeinePersonen");
                });

            modelBuilder.Entity("UtilsBot.Domain.BotSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("UtilsBot.Domain.WarEraContract", b =>
                {
                    b.Property<string>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastPerK")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ContractId");

                    b.ToTable("WarEraContracts");
                });

            modelBuilder.Entity("UtilsBot.Domain.WarEraContractMessage", b =>
                {
                    b.Property<string>("ContractId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractId", "ChannelId");

                    b.ToTable("WarEraContractMessages");
                });

            modelBuilder.Entity("UtilsBot.Domain.WarEraSubscription", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeProContracts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaximumDamage")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumRate")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("WarEraSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
