// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilsBot.Datenbank;

#nullable disable

namespace UtilsBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("UtilsBot.Domain.Models.AllgemeinePerson", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BekommtZurzeitSoVielXp")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BenachrichtigenZeitBis")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BenachrichtigenZeitVon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WillBenachrichtigungenBekommen")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Xp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ZuletztImChannel")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("AllgemeinePerson", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
